name: Deploy Angular App to GitHub Pages

on:
  # Runs on pushes targeting the 'main' branch
  push:
    branches: ["main"]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project 🔧
        run: |
          node optimize-images.js
          npm run build -- --base-href /LettersofConnection/
          cp dist/lettersof-connection/browser/index.html dist/lettersof-connection/browser/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist/lettersof-connection/browser

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
